[package]
name = "words"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
rustc-hash = "1.1.0"

[dependencies]
rand = { version = "0.8.5", default-features = false }
rand_core = { version = "0.6.4", default-features = false }
rustc-hash = "1.1.0"

